server {
  listen 80;
  server_name _;

  root /var/www/html/public;
  index index.php index.html;

  sendfile off;

  # Render logging
  access_log /dev/stdout;
  error_log /dev/stderr warn;

  charset utf-8;

  # Security headers
  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-Content-Type-Options "nosniff";

  # Block git access
  location /.git {
    deny all;
    return 403;
  }

  # Main Laravel routing
  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  # Ignore common files
  location = /favicon.ico { access_log off; log_not_found off; }
  location = /robots.txt  { access_log off; log_not_found off; }

  # Static assets
  location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|ttf|svg)$ {
    expires 5d;
    access_log off;
    log_not_found off;
  }

  # PHP-FPM
  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_pass unix:/var/run/php-fpm.sock;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }

  # Deny hidden files (.env, .git, etc)
  location ~ /\.(?!well-known).* {
    deny all;
  }
}